### ISSUE TITLE
robotite komponentide ostunimekirja koostamine

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics/robotont#1]
@andresmihkelson
kõigi robotikomponentide ostunimekirja (koos hindadega koostamine). ostunimekirja detailsus peab olema selline, et selle põhjal saab hinnata ühe roboti hinda ja esitada komponentide tellimusi.

**Comment by kruusamae** [comment]
ping

**Comment by andresmihkelson** [comment]
Kokkuvõtlik tabel koos ettepanekutega, kes ja mida tellida võiks:
https://docs.google.com/spreadsheets/d/1cD3bWUw_H7CeY20hMFYar38uP5hb0BwudrYnKfCkO2g/edit#gid=0
Lingid, kommentaarid jmt:
https://docs.google.com/document/d/1AgvtnB7PtbcxA_Hu9Kh9j-bwNilx7DhMehR3pxWTwJU/edit

**Comment by kruusamae** [comment]
@andresmihkelson 
väga kena! tundub mõistlik. ma eeldan, et siin on nüüd kõik roboti komponendid kirjas?
kas saaks tekitada nende asjade kohta, mida mina tellima pean, lingid koos tootekoodide ja lõplike kogustega. telliksin võimalikult kiiresti ära. realsense kaamerad on juba olemas.
ja telli need asjad ka ära, millel sinu nimi taga on.

**Comment by andresmihkelson** [comment]
**Hobbykingi tellimus:**
Kindlasti tuleb enne millegi ostukorvi lisamist valida Euroopa ladu.

Akud (vähemalt 6 tk, või kui eelarve võimaldab, siis igale robotile kaks) - https://hobbyking.com/en_us/multistar-high-capacity-4s-5200mah-multi-rotor-lipo-pack.html
Akualarmid (6 tk) - 
https://hobbyking.com/en_us/hobbykingtm-lipo-voltage-checker-2s-8s.html
Isased XT60 pistikud (2 kotti = 10 pistikut)
https://hobbyking.com/en_us/male-xt60-connectors-5pcs-bag-genuine.html

**Comment by andresmihkelson** [comment]
**Rataste kinnitused**
https://www.technobotsonline.com/universal-coupling-insert-6mm.html
18tk

**Omnirattad**
https://www.vexrobotics.com/vexedr/products/accessories/motion/edr-wheels.html
Ülevalt paremalt valida UK lipp - Euroopa alt tellides on saatmine oluliselt kallim
10 kahe rattaga komplekti - VEX 2.75'' double roller (276-1902)
(kaks ratast varuks, sest neid peab käsitsi ümber puurima jmt)
