### ISSUE TITLE
NUC-ide tellimine

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics/robotont#10]

**Comment by andresmihkelson** [comment]
Markitist tellitud, jääb oodata vaid tarnet.

**Comment by kruusamae** [comment]
kui kohale jõuavad, siis võib _issue_ sulgeda.

**Comment by kruusamae** [comment]
kohal, IT osakond pani mälu ja ssd sisse. ootavad esimest Ubuntu + ROS installi, et teha tõmmised
