### ISSUE TITLE
Robotite elektroonika komponentide tellimine

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics/robotont#11]
@andresmihkelson
ma saan aru, et hetkel tähendab see neid mbed plaate ainult?

**Comment by andresmihkelson** [comment]
Mbed plaadid, mõned ühenduspistikud, toitelülitid.

**Comment by kruusamae** [comment]
kas oled juba teedule nimekirja edastanud?

**Comment by andresmihkelson** [comment]
Pean vaatama homme üle mootoriplaadid - veenduma, et neile on peale joodetud kõik vajalikud pistikud (need on võrdlemisi kallid ja üleliia ei telliks neid).

Muus osas on nimekiri koos.

**Comment by kruusamae** [comment]
Teet tõi mulle ühe Farnelli paki, kus on plaadid ja pistikud sees.
