### ISSUE TITLE
ROS draiveri implementatsioon

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics/robotont#2]
C++ (eelistatud) või Pythoni implementatsioon base_controllerist, mis juhib üle jadaliidese roboti liikumist. Sisendina tellib /cmd_vel teemat. Lõpptulemus peaks olema kasutatav ROS move_base tarkvarakomplektiga.

**Comment by kruusamae** [comment]
@raidv , kas see _commit_ ( ca7c6723ec04be647b2e948a48b6088eed709e6c ) tähendab, et antud _issue_ on nüüd lahendatud ja valmis sulgemiseks?

**Comment by raidv** [comment]
Jah, esimeses lähendus küll. @kruusamae
