### ISSUE TITLE
robotont draiveri testimine mõne arvutimängupuldiga

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics/robotont#6]
@raidv
Testida robotont_driverit mistahes arvutimängupuldiga. Nt kasutades ROS joy'd (http://wiki.ros.org/joy) ja DroidTrick äppi.

http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick
http://wiki.ros.org/joy/Tutorials/WritingTeleopNode

**Comment by raidv** [comment]
@kruusamae ma arvan, et selle võib ka praegu lugeda lõpetatuks
https://drive.google.com/open?id=0B_G4AjnFIidMaEpyLUgxcTZfTWc

**Comment by kruusamae** [comment]
äge!
