### ISSUE TITLE
Juhend 1: Roboti juhtimine nutitelefoniga

### ISSUE THREAD

**Issue by kruusamae** [ut-ims-robotics/robotont#7]
Luua vormistatud tööjuhend töötoale, mille sisuks on robotondi juhtimine oma nutitelefoniga. Vt #6

Töövahendid: robotont, sülearvuti (Ubuntu ja ROS) ning nutitelefon (android, iOS)

Kirjalikus juhendis peab sisalduma samm-sammuline juhis.

**Comment by kruusamae** [comment]
@OSellis kas saaksid selle juhendi koostamise enda peale võtta?

**Comment by OSellis** [comment]
Vôin teha

Sent from my Windows Phone
________________________________

**Comment by OSellis** [comment]
Tegin sellise asja, kuidas tundub? Teen inglise keelse variandi ka, kui on ok

https://docs.google.com/document/d/1jmj5yV-v4vUIHzJJp7cGWMF0bVTkTBP8dh327WtkBUU/edit?usp=sharing

**Comment by raidv** [comment]
@OSellis Vaatsin ka läbi. Kuna dokumenti kommenteerimise õigust ei olnud, siis kirjutasin sulle eraldi endapoolset tagasisidet natuke tõsisemate ja vähemtõsisemate probleemide kohta.

**Comment by kruusamae** [comment]
@OSellis ingliskeelset pole esialgu tarvis, aga tee nii, et saaksime otse faili tagasisidet panna, vähemalt "suggesting" režiimis.
