### ISSUE TITLE
ROSi terminoloogia eestistamine

### ISSUE THREAD

**Issue by raidv** [ut-ims-robotics/robotont#9]
Kuna meil juba giti terminoloogia eestistamine on aktuaalne Issue, siis mõtlesin, et lisan siia ka ROSi teemalise küsimuse, kuna nüüd, kui rohkem kirja hakkasin panema asju, tekkis vajadus mõningate terminite järele.
Ega seesugust eestistatud terminoloogiat veel kusagil ei leidu?
Katsun siia jooksvalt lisada ka enda poolseid eestistusi, et siis kambakesi saaks nende sobivuse üle diskuteerida.

**Comment by raidv** [comment]
Panen siia kirja mõningad väljendid, mida juba kuskil kasutasin tõlgitult. Nõustuge ja vaielge siin all, siis saame väljendid, mis enamuse arust on loogilised ja mugavad kasutada :)

Robot Operating System - Roboti Operatsioonisüsteem
Node - Sõlm
Message - Sõnum
Package - Pakk?
Topic - Teema
Service - Teenus
Publisher - ?
Subscriber - ?
Publish - avaldama mingil teemal
Subscribe - jälgima mingit teemat
Navigation Stack - Navigatsiooni pinu?
Move_base - liikumisbaas?
Service request - Teenuse päring
Service response - Teenuse vastus
Roscore - viitan sellele kui "põhiprogramm" (kasutan ikkagi ka roscore väljendit sealjuures)
Distribution - Versioon?

**Comment by kruusamae** [comment]
Ma kunagi aasta tagasi eestindasin osasid termineid järgnevalt:

Tuum („roscore“) – jookseb alati taustal, viib sõlmi omavahel kokku
Sõlm („node“) – konkreetsele ülesandele pühendatud programm
Sõnum („message“) – platvormi-ülene muutujatüüp, kombineeritav
Teema („topic“) – sõne, mis annab sõnumivoole tähenduse
Kuulutaja („publisher“) – kuulutab sõnumeid kindlal teemal
Tellija („subscriber“) – võtab vastu sõnumeid antud teemal
Teenus („service“) – päringusõnum ja vastus
Toiming („action“) – päring, tagasiside ja tulemus 
Teenus („service“) – päringusõnum ja vastus
Toiming („action“) – päring, tagasiside ja tulemus 
Lansseerimine („launch“) – mitme sõlme käivitamine 

Ei väida, et minu pakutud on just need kõige paremad. Näiteks mulle esmapilgul täitsa meeldib "jälgima" "subscribe" tähenduses.

package'ile oleks küll hädasti head eestikeelset tõlget tarvis - ise olen mõelnud ka "komplekt" või "kogum" või "punt" või "kimp"

"stack" ei ole kindlasti pinu! See on tegelikult taanduv termin ROS-i terminoloogias ning enam seda väga ei soosita. Võib vabalt asendada ingliskeelse library'iga ehk eesti keeles nt "teek".

Kas "distribution" osas mingit eestindatud linuxi terminoloogiat aluseks ei saaks võtta? "Versioon" ei ole hea, sest peagi tuleb välja ROS2 ja siis hakkame rääkima versioonidest.

"move_base" on konkreetse teegi nimi ning seda tõlkima ei pea, minu arust.

Igasugu kommentaarid, arvamised oodatud!
@raidv @andresmihkelson @RValner @OSellis

**Comment by kruusamae** [comment]
@nowittyusername @maidlam @martinappo @Veix123 siin vestluses on ripakil üks arutelu ROSi terminoloogia eestindamise üle. kõik ideed/ettepanekud/mahategemised on teretulnud.

**Comment by kruusamae** [comment]
https://term.eki.ee/termbase/view/1418985/
